t = input('Digite algo: ')
print(t.isnumeric())
print(t.isalnum())
print(t.isalpha())
print(t.isascii())
print(t.isdecimal())
print(t.isidentifier())
print(t.islower())
print(t.isprintable())
print(t.isspace())
print(t.isdigit())
print(t.istitle())
print(t.isupper())
